# Generated by Django 3.0.6 on 2020-05-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_event_extrainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='name',
        ),
    ]
