# Generated by Django 3.0.6 on 2020-05-17 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200517_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Label'),
        ),
    ]
