# Generated by Django 3.0.6 on 2020-05-17 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200517_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
