# Generated by Django 3.0.6 on 2020-05-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_extrainfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extrainfo',
            old_name='extra_info',
            new_name='info',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_infos', to='catalog.Event'),
        ),
    ]
